export ZSH_AUTOSUGGEST_STRATEGY=(history completion);
export ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=50;
export ZSH_AUTOSUGGEST_USE_ASYNC=1
#export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#808080"
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#626861";

export ZSH_HIGHLIGHT_PATTERNS=('rm -rf *' 'fg=white,bold,bg=red');