export default {
  apps: "",
  calendar: "",
  clock: "",
  circle: "",
  circle1: "",
  circle2: "",
  circle3: "",
  circle4: "",
  circle5: "",
  cpu: "",
  memory: "",
  gpu: "",
  microphone: {
    normal: "",
    muted: "",
  },
  volume: {
    muted: "",
    normal: "",
  },
  mpris: {
    default: "",
    fallback: "audio-x-generic-symbolic",
    backward: "",
    play: "",
    pause: "",
    stop: "",
    forward: "",
  },
  trash: "",
  notifications: {
    indicator: "",
    dnd: "",
  },
  video: "",
  camera: "",
  stop: "",
  search: "",
  powerMenu: {
    shutdown: "",
    reboot: "",
    logout: "",
  },
};
