#!/bin/sh

## Setting environment variables for wayland session
# export XDG_SESSION_TYPE=wayland
# export XDG_SESSION_DESKTOP=Hyprland
# export XDG_CURRENT_DESKTOP=Hyprland
# export XDG_CURRENT_SESSION=hyprland
#
# ## GTK environment
# export TDESKTOP_DISABLE_GTK_INTEGRATION=1
# export CLUTTER_BACKEND=wayland
# export BEMENU_BACKEND=wayland
#
# ## Firefox
# export MOZ_ENABLE_WAYLAND=1
#
# ## Qt environment
# export QT_QPA_PLATFORM=wayland-egl #error with apps xcb
# export QT_WAYLAND_FORCE_DPI=physical
# export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
# export QT_AUTO_SCREEN_SCALE_FACTOR=1
#
# ## SDL environment
# export SDL_VIDEODRIVER=wayland
#
# # Nvidia stuff
# export WLR_NO_HARDWARE_CURSORS=1
# export LIBVA_DRIVER_NAME=nvidia
# export GBM_BACKEND=nvidia-drm
# export __GLX_VENDOR_LIBRARY_NAME=nvidia
#
#
#
# export NO_AT_BRIDGE=1
# export WINIT_UNIX_BACKEND=wayland
# export DBUS_SESSION_BUS_ADDRESS
# export DBUS_SESSION_BUS_PID

## Start Hyprland
sleep 0.5
exec Hyprland
