#!/usr/bin/env bash

iDIR="$HOME/.config/dunst/icons"
notify_cmd='notify-send -h string:x-canonical-private-synchronous:sys-notify -u low'


if ! command -v light &> /dev/null
then
    $notify_cmd "'light' is not installed."
    exit 1
fi


# Get brightness
get_backlight() {
	LIGHT=$(printf "%.0f\n" `light -G`)
	echo "${LIGHT}%"
}

# Get icons
get_icon() {
	backlight="$(get_backlight)"
	current="${backlight%%%}"
	if [[ ("$current" -ge "0") && ("$current" -le "20") ]]; then
		icon="$iDIR/brightness-20.png"
	elif [[ ("$current" -ge "20") && ("$current" -le "40") ]]; then
		icon="$iDIR/brightness-40.png"
	elif [[ ("$current" -ge "40") && ("$current" -le "60") ]]; then
		icon="$iDIR/brightness-60.png"
	elif [[ ("$current" -ge "60") && ("$current" -le "80") ]]; then
		icon="$iDIR/brightness-80.png"
	elif [[ ("$current" -ge "80") && ("$current" -le "100") ]]; then
		icon="$iDIR/brightness-100.png"
	fi
}

# Notify
notify_user() {
	$notify_cmd -i "$icon" "Brightness : $(get_backlight)"
}

# Increase brightness
inc_backlight() {
	light -A 5 && get_icon && notify_user
}

# Decrease brightness
dec_backlight() {
	light -U 5 && get_icon && notify_user
}

# Set brightness
set_backlight() {
  light -S $1
}

case $1 in
    --value)
        get_backlight
    ;;
    --up)
        inc_backlight
    ;;
    --down)
        dec_backlight
    ;;
    --set)
      set_backlight $2
    ;;
    --help | *)
        echo "usage: backlight [OPTIONS]
		
OPTIONS
   --value
   --up
   --down
   --set [value]
"
    ;;
esac

