#!/usr/bin/env bash

notify_cmd='notify-send -h string:x-canonical-private-synchronous:sys-notify -u low'

check_command(){
  if ! command -v $1 &> /dev/null
  then
    $notify_cmd "'$1' is not installed."
    exit 1
  fi
}

lock_wayland(){
  check_command swaylock

  # Colors
  bg='20262C'
  bgl='343A40'
  fg='F1FCF9'
  red='DB86BA'
  green='74DD91'
  yellow='E49186'
  blue='75DBE1'
  magenta='B4A1DB'
  cyan='9EE9EA'
  alpha='00000000'

  # Background Image
  IMAGE="$HOME/.config/hypr/wallpapers/lockscreen.png"

  # CMD
  swaylock -f \
    \
    `# General` \
    --ignore-empty-password \
    --show-failed-attempts \
    --hide-keyboard-layout \
    --indicator-caps-lock \
    \
    `# Appearance` \
    --color ${bg}E6 \
    `#--image ${IMAGE} --scaling fill` \
    --font 'CartographCF Nerd Font' --font-size 18 \
    \
    `# Backspace Key` \
    --key-hl-color ${green} \
    --caps-lock-key-hl-color ${blue} \
    --bs-hl-color ${red} \
    --caps-lock-bs-hl-color ${red} \
    \
    `# Indicator` \
    --indicator-radius 120 \
    --indicator-thickness 10 \
    \
    `# Inside Circle Colors` \
    --inside-color ${alpha} \
    --inside-clear-color ${alpha} \
    --inside-caps-lock-color ${alpha} \
    --inside-ver-color ${blue} \
    --inside-wrong-color ${red} \
    \
    `# Layout Colors` \
    --layout-bg-color ${cyan} \
    --layout-border-color ${cyan} \
    --layout-text-color ${bg} \
    \
    `# Line Colors` \
    --line-color ${bg} \
    --line-clear-color ${red} \
    --line-caps-lock-color ${bg} \
    --line-ver-color ${bg} \
    --line-wrong-color ${bg} \
    \
    `# Ring Colors` \
    --ring-color ${cyan} \
    --ring-clear-color ${bg} \
    --ring-caps-lock-color ${magenta} \
    --ring-ver-color ${blue} \
    --ring-wrong-color ${red} \
    \
    `# Separator Color` \
    --separator-color ${bg} \
    \
    `# Text Colors` \
    --text-color ${fg} \
    --text-clear-color ${fg} \
    --text-caps-lock-color ${fg} \
    --text-ver-color ${bg} \
    --text-wrong-color ${bg}
}

lock_X11() {
  check_command i3lock
  
  font="dedede"
  green="9ece6a"
  red="db4b4b"

  i3lock -n \
  --force-clock \
  --fill -i $IMAGE \
  --ignore-empty-password \
  --refresh-rate=1 --line-uses-inside --pointer=default --pass-media-keys --pass-volume-keys --pass-screen-keys \
  --inside-color="$green" --ring-color="$green" --insidever-color="$green" --ringver-color="$green" --insidewrong-color="$red" --ringwrong-color="$red" \
  --keyhl-color="$green" --separator-color="$green" --bshl-color="$green" --color=000000 \
  --time-str="%H:%M" --time-size=140 --time-pos="960:300" --time-font="CartographCF Nerd Font:style=Bold" --time-color="$font" \
  --date-str="%A %d %B" --date-size=45 --date-pos="960:380" --date-font="CartographCF Nerd Font" --date-color="$font" \
  --verif-text="Verifying" --greeter-text="" --wrong-text="Wrong Password!" --noinput-text="No input" \
  --verif-font="CartographCF Nerd Font"  --greeter-font="CartographCF Nerd Font" --wrong-font="CartographCF Nerd Font" \
  --verif-size=35 --greeter-size=35 --wrong-size=35 \
  --verif-pos="960:540" --greeter-pos="960:600" --wrong-pos="960:540" \
  --verif-color="$green" --greeter-color="$font" --wrong-color="$red"
}


if [[ "$XDG_SESSION_TYPE" == "wayland" ]]; then
  lock_wayland
else
  lock_X11
fi