#!/usr/bin/env bash

notify_cmd='notify-send -h string:x-canonical-private-synchronous:sys-notify -u low'

terminal="kitty"
terminal_cmd_arg=""

# terminal="alacritty"
# terminal_cmd_arg="-e"


if ! command -v $terminal &> /dev/null
then
	$notify_cmd "'$terminal' is not installed."
    exit 1
fi


VALID_ARGS=$(getopt -o fe:c:t: --long float,command:,class:,title: -- "$@")
if [[ $? -ne 0 ]]; then
    exit 1;
fi

eval set -- "$VALID_ARGS"
while [ : ]; do
  case "$1" in
    -f | --float)
      if [[ -n "$CLASS" ]]; then
        echo -e "Cannot have multiple class"
        exit 0
      fi
      CLASS="floating_terminal"
      shift
      ;;
    -e | --command)
      CMD=$2
      shift 2
      ;;
    -c  | --class)
      if [[ -n "$CLASS" ]]; then
        echo -e "Cannot have multiple class"
        exit 0
      fi
      CLASS="$2"
      shift 2
      ;;
    -t | --title)
      TITLE="$2"
      shift 2
      ;;
    --)
      shift; 
      break 
      ;;
  esac
done

$terminal ${CLASS:+--class $CLASS} ${TITLE:+--title $TITLE} ${CMD:+$terminal_cmd_arg $CMD}

